### ISSUE TITLE
Ругается в лог при ребейзе

### ISSUE THREAD

**Issue by silentroach** [jehy/husky-add-issue-tracker#11]
Если в ветке запустить rebase на master, например, то при применении каждого из коммитов в лог неплохо поднасрёт ошибками:

```bash
[своя ветка]$ git rebase master
husky > prepare-commit-msg (node v12.19.0)
grep: bin: Is a directory
grep config: Is a directory
grep coverage: Is a directory
(и так на каждую папку в текущей папке проекта)
```

macos, zsh (на bash то же самое).  Верю, что под вендой будет вообще треш )

```git branch | grep *```

Выдает то же самое.

**Comment by silentroach** [comment]
Во, а вот если звездочку экранировать – получается кул

```bash
[/Volumes/Projects/qwerty]$ git branch | grep \*
* feature/KEK-61-lel
```

**Comment by jehy** [comment]
Ага, поправил в 0.1.1.
